services:
  aegix:
    build: .
    container_name: aegix-app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./configs:/app/configs
      - ./frontend:/app/frontend
    env_file:
      - ./configs/aegix.env
    depends_on:
      - db
    command:
      ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
    entrypoint: ["/bin/bash", "/app/entrypoint.sh"]

  db:
    image: postgres:13
    container_name: postgres-aegix
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: aegix
      POSTGRES_PASSWORD: aegix
      POSTGRES_DB: aegix
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
networks:
  default:
    name: aegix_network
